### ISSUE TITLE
Movies List

### ISSUE THREAD

**Issue by JessicaLoers** [JessicaLoers/Capstone-Project-MovieMagic#1]
### Value Proposition
**As a user**,
**I want to** see a list of current movies
**so that I** can quickly discover and explore the latest films.

### Description
![Image](https://user-images.githubusercontent.com/54777853/267121986-6cc9d4c5-9ee5-479a-b4a6-18e7f867b6a7.png)

### Acceptance Criteria
- [ ] On the home page, there is a list of current movies displayed
- [ ] Each movie in the list includes the following details:
  - The movie's title
  - The poster image of the movie
  - The movie's rating.
- [ ]  If there is an issue loading movie data from the source, an error message is displayed to the user.
- [ ] The movie list is vertically scrollable

### Tasks

- [ ] Create the feature branch `feature/movies-list`
- [ ] Fetch a list of current movies from The MovieDB API
   - [ ] Add error handling logic to display an error message if there's an issue loading movie data from the API.
- [ ] Build the `Movie` component responsible for rendering movie details:
   - [ ] the name of the movie
   - [ ] the poster image of the movie
   - [ ] the rating of the movie
- [ ]  Build the `MovieList` component that:
   - [ ] maps through the fetched list of movies 
   - [ ] renders a `Movie` component instance for each movie
- [ ] Integrate the `MovieList` component into `pages/index.js`

**Comment by Sky-De** [comment]
@JessicaLoers hi, please assign this to me, i would like to fix this problem,
After PR i will ask for the other issue assignment 
Thanks
