### ISSUE TITLE
Movie Details

### ISSUE THREAD

**Issue by JessicaLoers** [JessicaLoers/Capstone-Project-MovieMagic#2]
### Value Proposition
**As a user**,
**I want to** to view detailed information about a specific movie
**so that I can** make informed decisions about which movies to watch

### Description
![Image](https://user-images.githubusercontent.com/54777853/267130170-239b02d7-a8a3-4e21-b9a3-72c87574075d.png)

### Acceptance Criteria
- [ ] When users select a movie from the movies list on the homage, they should be redirected to a dedicated movie details page.
- [ ] On the movie details page, users should be presented with the following information:
  - The movie's poster
  - The movie's title
  - The movie's release date
  - A detailed description of the movie's plot
- [ ] The movie details page should include a dedicated "Back to Home" button at the top, allowing the user to easily return to the homepage

### Tasks

- [ ] Create the feature branch `feature/movie-details`
- [ ] Develop the movie details page `pages/movies/[id].js` ensuring that it:
  - [ ] Render/displays the movie's poster, title, release date, and description
  - [ ] Includes a next.js `Link` component to enable users to navigate back to the homepage `pages/index.js`
- [ ] Update the `Movie` component 
  - [ ] Include a next.js `Link` component that directs users to the movie details page
